#!/bin/sh
#
# Starts atguigu-gateway
#

start() {
	# delete old logfile
	rm -rf /var/log/atguigu-gateway.log

	# update bin
	if [ -f "/tmp/atguigu-gateway.update" ]; then
		chmod 755 "/tmp/atguigu-gateway.update" &&
			mv -f "/tmp/atguigu-gateway.update" "/usr/bin/atguigu-gateway"
	fi

	printf "Starting atguigu-gateway: "

	start-stop-daemon -S -q --exec /usr/bin/atguigu-gateway -- daemon
	result=$?
	[ $result = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping atguigu-gateway: "
	start-stop-daemon -K -q -x /usr/bin/atguigu-gateway daemon
	result=$?
	[ $result = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart | reload)
	restart
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

exit $result
